// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbUb805bg6Ykv_F830olZtlxnn5Ue5S4',
    appId: '1:584215442921:web:09622a77ab650d5fcc0778',
    messagingSenderId: '584215442921',
    projectId: 'firstproject-8bbc5',
    authDomain: 'firstproject-8bbc5.firebaseapp.com',
    storageBucket: 'firstproject-8bbc5.appspot.com',
    measurementId: 'G-MZ0PYZK1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGuPyFB3-X6bQVO-9X42TaSKUvvxEi38',
    appId: '1:584215442921:android:e86ab7cda53ccdbecc0778',
    messagingSenderId: '584215442921',
    projectId: 'firstproject-8bbc5',
    storageBucket: 'firstproject-8bbc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIVI3mBmbWztbwPoCe6fcFHFsHOi_9Ec',
    appId: '1:584215442921:ios:12d56025fd31a4c5cc0778',
    messagingSenderId: '584215442921',
    projectId: 'firstproject-8bbc5',
    storageBucket: 'firstproject-8bbc5.appspot.com',
    iosBundleId: 'com.example.gdgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIVI3mBmbWztbwPoCe6fcFHFsHOi_9Ec',
    appId: '1:584215442921:ios:12d56025fd31a4c5cc0778',
    messagingSenderId: '584215442921',
    projectId: 'firstproject-8bbc5',
    storageBucket: 'firstproject-8bbc5.appspot.com',
    iosBundleId: 'com.example.gdgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxbUb805bg6Ykv_F830olZtlxnn5Ue5S4',
    appId: '1:584215442921:web:f46fb100b5214e58cc0778',
    messagingSenderId: '584215442921',
    projectId: 'firstproject-8bbc5',
    authDomain: 'firstproject-8bbc5.firebaseapp.com',
    storageBucket: 'firstproject-8bbc5.appspot.com',
    measurementId: 'G-QER6BPQ73E',
  );

}